### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nopzen** [artis3n/ansible-role-tailscale#182]
**describe the bug**
Once I run the play book (see playbook.yaml) the system errors on the ansible role.

**Playbook**
```yaml
---
- name: Setup virtual machine tools & users
  hosts: all
  remote_user: root

  tasks:
  - name: Ping machines
    ping:
  - name: Update & Upgrade ubuntu packages
    apt:
      upgrade: "yes"
      update_cache: true
      cache_valid_time: 86400

  - name: Configure Tailscale
    include_role:
      name: artis3n.tailscale
    vars:
      verbose: true
      tailscale_args: "--accept-routes=true"
      # Pulled from the env vars on the host running Ansible
      tailscale_auth_key: "{{ lookup('env', 'TAILSCALE_KEY') }}"

```

**Error**
```bash
ERROR! this task 'ansible.builtin.include_tasks' has extra params, which is only allowed in the following modules: include, include_tasks, command, meta, set_fact, add_host, import_tasks, win_shell, shell, win_command, include_role, raw, group_by, import_role, script, include_vars

The error appears to be in '/root/.ansible/roles/artis3n.tailscale/tasks/main.yml': line 55, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: CentOS and related families
  ^ here
```

**Operating System**
local machine: Windows WSL 2 (Ubuntu)
target machines: Ubuntu 20.04

I'm wondering if im doing anything wrong? I'm fairly new to Ansible, but I was trying to use the simple examples in the README.md
