### ISSUE TITLE
[BUG] Tailscale up command quotes break the command

### ISSUE THREAD

**Issue by Daxcor69** [artis3n/ansible-role-tailscale#203]
**Describe the bug**
my tailscale won't authenticate with auth key or api key.   the error message doesn't make sense, You don't pass the api key, so why would it be not correct.  I tried to send on any way. 

**To Reproduce**
```
---
- name: Servers
  hosts: gateway
  gather_facts: yes
  become: no

  tasks:
    - name: Configure Sysctl
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        ignoreerrors: true
        sysctl_set: true

    - name: Configure Tailscale
      include_role:
        name: artis3n.tailscale

      vars:
        tailscale_args: "--accept-routes=true --advertise-routes=10.0.1.0/24"
        # Pulled from the env vars on the host running Ansible
        tailscale_authkey: "blah blah"
```

**Expected behavior**
Tailscale would show as active.

**Screenshots**

**Target (please complete the following information):**
 - OS:  Ubuntu 20.04 minimal
 - Ansible version: ansible [core 2.12.5]
 - `artis3n.tailscale` version:   latest
 

** outputs:**

TASK [artis3n.tailscale : Get Existing State Checksum] ***************************************************************************************************************************************************
task path: /home/bd/.ansible/roles/artis3n.tailscale/tasks/lib/up-state.yml:2
fatal: [10.0.1.2]: FAILED! => {"changed": false, "msg": "file not found: /home/bd/.artis3n-tailscale/.idempotency/state"}
...ignoring

TASK [artis3n.tailscale : Install | Report redacted failure from "tailscale up"] *************************************************************************************************************************
task path: /home/bd/.ansible/roles/artis3n.tailscale/tasks/install.yml:101
fatal: [10.0.1.2]: FAILED! => {"changed": false, "msg": ["backend error: invalid key: invalid API token"]}
