### ISSUE TITLE
[BUG] sudo: not found on Proxmox system

### ISSUE THREAD

**Issue by SebDanielsson** [artis3n/ansible-role-tailscale#283]
**Describe the bug**
I tried to run this role to bring up Tailscale on Proxmox and got this error message:
```sh
TASK [artis3n.tailscale : Debian | Apt Dependencies] ************************************
fatal: [hogsmeade]: FAILED! => {"changed": false, "module_stderr": "Shared connection to hogsmeade closed.\r\n", "module_stdout": "/bin/sh: 1: sudo: not found\r\nexit status 127\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**To Reproduce**
```
- name: Install and configure Tailscale
   role: artis3n.tailscale
     tailscale_args: "--ssh"
     vars:
       tailscale_authkey: <KEY>
```

Run this on Proxmox 7.3 and see the error.

**Expected behavior**
Tailscale should install and start.

**Target (please complete the following information):**
 - OS: Proxmox 7.3
 - Ansible version: 2.14.1
 - `artis3n.tailscale` version: 3.5.0
 - Tailscale version (set `verbose` to true): Should be latest for Debian?

**Comment by artis3n** [comment]
Looks like `sudo` isn't available on the target system. Before invoking this role, I'd run

```bash
apt update && apt install sudo
usermod -aG sudo <your_username>
```

or:

```yml
- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    cache_valid_time: 3600

- name: Add user to sudo group
  ansible.builtin.user:
    name: <your_username>
    append: true
    groups: sudo
```

Does that resolve the error?
