### ISSUE TITLE
The conditional check 'tailscale_original_distribution_major_version == \"NA\"' failed

### ISSUE THREAD

**Issue by itinfserv** [artis3n/ansible-role-tailscale#306]
Hi, when running the role using role_include it throws an error:

`fatal: [localhost]: FAILED! => {"msg": "The conditional check 'tailscale_original_distribution_major_version == \"NA\"' failed. The error was: error while evaluating conditional (tailscale_original_distribution_major_version == \"NA\"): {{ ansible_distribution_major_version }}: 'ansible_distribution_major_version' is undefined\n\nThe error appears to be in '/home/xxx/.ansible/roles/artis3n.tailscale/tasks/main.yml': line 42, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Install lsb_release\n      ^ here\n"}`

```
  - name: Install Tailscale
    include_role:
      name:  artis3n.tailscale
    vars:
      tailscale_authkey: "xxxx"
```

I have tried adding become: true and false wondering if its a user context thing but same error occurs.

**Comment by itinfserv** [comment]
Sorry I should add that using roles works fine, its just include_roles

this works:

```
- hosts: localhost
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "xxxx"
```

I need to use roles_include rather than roles because the roles method doesnt seem to work with an include file and I dont want the tailscale playbook in the main playbook as I want to encrypt it using vault
