### ISSUE TITLE
[BUG] authkey is logged even when insecurely_log_authkey is false

### ISSUE THREAD

**Issue by jorhett** [artis3n/ansible-role-tailscale#315]
**Describe the bug**

authkey is logged even when insecurely_log_authkey is false

**To Reproduce**

```yaml
 - name: Configure Tailscale
      ansible.builtin.include_role:
        name: tailscale
      vars:
        insecurely_log_authkey: false
        tailscale_authkey: "tskey-auth-SECRET-VALUE"
```

**Expected behavior**

The authkey would not be shown in the logs.

**Screenshots**

```
TASK [tailscale : Gather Up Arguments] *****************************************
ok: [35.85.207.202] => {
    "ansible_facts": {
        "tailscale_up_args": "--authkey=tskey-auth-SECRET-VALUE"
    },
    "changed": false
}
```

**Target (please complete the following information):**
 - OS: Ubuntu
 - Ansible version: 2.12.2
 - `artis3n.tailscale` version: v4.1.0
