### ISSUE TITLE
[FEAT] add additional URL-style --auth-key flag (ephemeral & preauthorized)

### ISSUE THREAD

**Issue by McSim85** [artis3n/ansible-role-tailscale#398]
Tailscale accepts additional URL-style parameters when used with OAuth secrets:

```sh
tailscale up --auth-key=${OAUTH_CLIENT_SECRET}?ephemeral=false&preauthorized=true --advertise-tags=tag:ci
```

**Describe the solution you'd like**
It will be nice to make it configurable via variables like:
```yml
- name: Servers
  hosts: all
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_ephemeral: true
        tailscale_preauthorized: false
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
```

**Additional context**

Documentation:
https://tailscale.com/kb/1215/oauth-clients/#registering-new-nodes-using-oauth-credentials
