### ISSUE TITLE
[FEAT] node does not cleanup from tailnet, when logouts

### ISSUE THREAD

**Issue by McSim85** [artis3n/ansible-role-tailscale#400]
Tailscale does not remove non-ephimeral nodes, even if `tailscale logout` run. 
Tailscale does remove ephemeral nodes, but it takes 30 minutes-48 hours.

So, if the role runs with the `state: present`, then with the `state: absent`, then run again with `state: present` on the same machine with the same hostname within 30 minutes window, then a new machine is created in tailnet, but with `-number` tail in the machine name.

How to reproduce (run this within 30 minutes time window):
### 1. install tailscale
```yaml
- name: Servers
  hosts: hostnameX
  roles:
    - role: artis3n.tailscale
      vars:
        state: present
```
### 2. UnInstall tailscale
```yaml
- name: Servers
  hosts: hostnameX
  roles:
    - role: artis3n.tailscale
      vars:
        state: absent
```
### 3. install tailscale
```yaml
- name: Servers
  hosts: hostnameX
  roles:
    - role: artis3n.tailscale
      vars:
        state: present
```

Then tailscale machine list contains 2 machines:
- `hostnameX` (expired)
- `hostnameX-1` (connected)

Which makes tailscale DNS discrepancies and using commands like `ssh hostnameX` does not work anymore:
```sh
$ ssh hostnameX                                                                            git:(main|…1
ssh: Could not resolve hostname hostnamex: nodename nor servname provided, or not known
```
But `ssh hostnameX-1` works.

**Describe the solution you'd like**
The idea is:
- add a variable `tailscale_purge: true` (default - `false`), that will trigger the purge machine record over API
- create a task list like this in `tasks/unistall.yml:
```yaml
- name: Get list of Tailscale devices
  uri:
    url: "https://api.tailscale.com/api/v2/tailnet/{{ your_tailnet }}/devices"
    method: GET
    headers:
      Authorization: "Bearer {{ tailscale_api_token }}"
    return_content: yes
  register: tailscale_devices
  when: tailscale_purge | bool

- name: Delete matching Tailscale devices
  uri:
    url: "https://api.tailscale.com/api/v2/device/{{ item.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ tailscale_api_token }}"
  loop: "{{ tailscale_devices.json.devices }}"
  when:
    - tailscale_purge | bool
    - item.name == ansible_hostname
```

**Describe alternatives you've considered**
The disadvantage of this: I am not sure if this works with a regular auth key. Probably, API key or OAuth key is required.  

**Additional context**
Relevant Tailscale issue
https://github.com/tailscale/tailscale/issues/8844
