### ISSUE TITLE
[FEAT] Improve tags support

### ISSUE THREAD

**Issue by McSim85** [artis3n/ansible-role-tailscale#406]
First off, a big thanks for the thumbs up on my last PR. Really appreciate it! 🙏

I am writing to propose some enhancements related to the handling of `tags` within the role. As you're aware, tags are crucial for assigning identities to devices, distinct from human user accounts, and are instrumental in ACL configurations for access restrictions. Multiple tags can be associated with a single device, enhancing flexibility and control.

## Current Implementation Challenges:

The existing `tailscale_oauth_tags` variable is designed to accept a string input. However, considering the possibility of assigning multiple tags to a device, it would be more logical for this variable to accept a list. I recommend simplifying the input to a list of strings. The "tag:" prefix could then be appended internally within the role, utilizing `set_fact` and `join` to construct the required string format.

## Additional Consideration – Regular Auth Key Compatibility:

The current setup also presents a challenge when using regular auth keys with tags and the `--advertise-tags` option. For example, in scenarios where an external role imports [ansible-role-tailscale](https://github.com/artis3n/ansible-role-tailscale) and utilizes different key types with tags, the preparatory handling of tags becomes cumbersome and format-dependent.

Consider the following example, which illustrates the complexity of the current approach:

```yaml
- name: String for a regular key
  ansible.builtin.set_fact:
    tailscale_tags_string: >-
      {# Check if the key is an OAuth key #}
      {% if tailscale_authkey.startswith('tskey-client-') %}
      {{ tagged_tailscale_tags | trim | join(',') }}
      {# Check if the key is not OAuth (regular authkey or unused) #}
      {% else %}
      "--advertise-tags={{ tagged_tailscale_tags | join(',') }}"
      {% endif %}

# in this import, I pass tags in tailscale_oauth_tags
- name: Install tailscale
  ansible.builtin.import_role:
    name: ansible_role_tailscale
  vars:
    state: "present" # noqa: var-naming[no-role-prefix]
    verbose: true
    tailscale_authkey: "{{ tailscale_auth_key }}"
    tailscale_args: "--timeout=120s"
    tailscale_oauth_ephemeral: "{{ tailscale_set_ephemeral | bool }}"
    tailscale_oauth_preauthorized: true
    tailscale_oauth_tags: "{{ tailscale_tags_string }}"
  when: tailscale_auth_key.startswith('tskey-client-')

# but in this import, tags become tailscale_args
- name: Install tailscale
  ansible.builtin.import_role:
    name: ansible_role_tailscale
  vars:
    state: "present" # noqa: var-naming[no-role-prefix]
    verbose: true
    tailscale_authkey: "{{ tailscale_auth_key }}"
    tailscale_args: "{{ tailscale_tags_string }} --timeout=120s"
  when: tailscale_auth_key.startswith('tskey-client-')
```

## Proposed Solution:

To streamline the process, I suggest the following changes:

- Rename Variable: Change `tailscale_oauth_tags` to `tailscale_tags`.
- Expected Input Format: Allow `tailscale_tags` to accept a list.
- Internal String Construction: Utilize `set_fact` and `join` to append "tag:" and build the final string.
- Error Handling: Implement a fail condition if `tailscale_tags` is empty and `tailscale_authkey` is an OAuth key.
- Parameter Inclusion: Conditionally add the `--advertise-tags` parameter based on the presence of tags.

With these modifications, the configuration becomes more intuitive and streamlined, as demonstrated below:

```yaml
- name: Install tailscale
  ansible.builtin.import_role:
    name: ansible_role_tailscale
  vars:
    state: "present"
    verbose: true
    tailscale_authkey: "{{ tailscale_auth_key }}"
    tailscale_args: "--timeout=120s"
    tailscale_tags: 
      - a
      - b
    tailscale_oauth_ephemeral: "{{ tailscale_set_ephemeral | bool }}"
    tailscale_oauth_preauthorized: true
```

I believe these enhancements will greatly benefit the usability and flexibility of the role. I look forward to discussing these suggestions further and, upon agreement, will proceed with submitting a PR. 👍
