### ISSUE TITLE
[BUG] Running the role with `state: absent` might break the `apt`

### ISSUE THREAD

**Issue by McSim85** [artis3n/ansible-role-tailscale#413]
**Describe the bug**
If I run the role on Debian family like this:
```yaml
- name: UnInstall tailscale
  ansible.builtin.import_role:
    name: ansible_role_tailscale
  vars:
    state: absent # noqa: var-naming[no-role-prefix]
    verbose: true # noqa: var-naming[no-role-prefix]
```
The next run of `apt update` will fail with the error:
```bash
<...REDACTED...>
Err:10 https://pkgs.tailscale.com/stable/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 458CA832957F5868
Fetched 6560 B in 1s (7200 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://pkgs.tailscale.com/stable/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 458CA832957F5868
W: Failed to fetch https://pkgs.tailscale.com/stable/ubuntu/dists/focal/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 458CA832957F5868
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@host:~# rm /etc/apt/sources.list.d/pkgs_tailscale_com_stable_ubuntu.list 
```
That happens because, the role deletes `Remove Tailscale Signing Key`, but does not remove the repo source. 

**Expected behavior**
Remove Tailscale source from the apt config

**Target (please complete the following information):**
 - OS: Debian family

**Additional context**
PR is under its way.
