### ISSUE TITLE
[BUG] tailscale status task output sometimes fails to parse as json

### ISSUE THREAD

**Issue by whysthatso** [artis3n/ansible-role-tailscale#421]
**Describe the bug**
I'm not certain if this is a bug. I'm running the role like this:

```
    - name: include tailscale role
      ansible.builtin.include_role:
        name: git.artis3n.tailscale
```
and  I'm getting this error:

```
TASK [git.artis3n.tailscale : Install | Parse status JSON] ******************************************************************************************************************************************************
fatal: [docker-host-1]: FAILED! => {}                                                                                                                                                                            
                                                                                                                                                                                                                 
MSG:                                                                                                                                                                                                             
                                                                                                                                                                                                                 
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'Self'. 'dict object' has no attribute 'Self'                                                              
                                                                                                                                                                                                                 
The error appears to be in '/home/user/ansible/roles/git.artis3n.tailscale/tasks/install.yml': line 67, column 3, but may                                                                    
be elsewhere in the file depending on the exact syntax problem.                                                                                                                                                  

The offending line appears to be:


- name: Install | Parse status JSON
  ^ here
```
Everything is dandy when i run it traditionally:

```
  roles:
    - git.artis3n.tailscale
```
Is this related on how facts  get set, and that `include_role` works differently here?

**Comment by jsenecal** [comment]
I actually have experienced the same issue. Let me know if you would need how I could help with troubleshooting/resolving this.

This is how it is invoked here:
```
- name: Install tools
  hosts:
    - qix_oob
  become: yes
  strategy: free
  vars_prompt:
    - name: tailscale_authkey 
      prompt: Tailscale authkey?
      private: true
  tasks:
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - tcpdump
        - iperf3
        - netcat
  roles:
    - role: artis3n.tailscale
```

When ran the second time, the error message is gone.
