### ISSUE TITLE
[BUG] Unistall can be broken in some scenarios

### ISSUE THREAD

**Issue by McSim85** [artis3n/ansible-role-tailscale#429]
**Describe the bug**
Running the role with 
```yaml
- name: UnInstall tailscale
  ansible.builtin.include_role:
    name: ansible_role_tailscale
  vars:
    state: absent # noqa: var-naming[no-role-prefix]
    verbose: true # noqa: var-naming[no-role-prefix]
    tailscale_tags: ['sometag']
```

Might fail with the error:
```yaml
TASK [ansible_role_tailscale : Uninstall | De-register Tailscale Node] *********
fatal: [host]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  cmd: tailscale status; tailscale logout
  delta: '0:00:00.104574'
  end: '2024-02-13 02:29:31.996263'
  msg: non-zero return code
  rc: 1
  start: '2024-02-13 02:29:31.891689'
  stderr: '500 Internal Server Error: invalid key: API key kzTEHB4CNTRL not valid'
  stderr_lines: <omitted>
  stdout: |-
    # Health check:
    #     - not logged in, last login error=invalid key: API key kzTEHB4CNTRL not valid
  
    unexpected state: NoState
  stdout_lines: <omitted>
```

That happens because during execution these tasks:
https://github.com/artis3n/ansible-role-tailscale/blob/dd09d2f1df9e09bcd1b5e51bbafe608082ff7e9e/tasks/uninstall.yml#L2-L18

The `tailscale status` exits with exit code 1 and then `tailscale logout` exit code 1:
```
root@host:~# tailscale status
# Health check:
#     - not logged in, last login error=invalid key: API key kX1yFH7CNTRL not valid

unexpected state: NoState
root@host:~# echo $?
1
root@host:~# tailscale logout
500 Internal Server Error: invalid key: API key kX1yFH7CNTRL not valid
root@host:~# echo $?
1
```

**Expected behavior**
Do not fail in such scenarios.

**Additional context**
PR is coming. :)
