### ISSUE TITLE
[FEAT] Allow specifying the playbook state directory

### ISSUE THREAD

**Issue by neilschelly** [artis3n/ansible-role-tailscale#471]
**Is your feature request related to a problem? Please describe.**
We have multiple users who might run ansible configuration playbooks against a given system. Since the state for the playbook is stored in a user-specific state directory based on either `env.XDG_STATE_HOME` or `env.HOME`, that means that the current state isn't always found depending on who runs the ansible commands.

**Describe the solution you'd like**
I think the best solution would be allowing a variable like `tailscale_state_directory` that could override the following `set_fact` declaration in the playbook. It would have to be a shared folder that allows multiple users to read/write it too.

```
- name: Install | Determine state folder
  ansible.builtin.set_fact:
    # Following https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
    tailscale_state_folder: "{{ ansible_env.XDG_STATE_HOME | default(ansible_env.HOME + '/.local/state') }}"
```
