### ISSUE TITLE
[FEAT] Enable IPv4 and IPv6 forwarding

### ISSUE THREAD

**Issue by GarrisonD** [artis3n/ansible-role-tailscale#487]
That would be cool to have the role enabling IP forwarding as described in [Enable IP forwarding](https://tailscale.com/kb/1019/subnets?tab=linux#enable-ip-forwarding)

Here is how I do it now in the playbook just before the `tailscale` role:

```yml
---
- name: Enable IPv4 forwarding
  ansible.posix.sysctl: { name: net.ipv4.ip_forward, value: 1 }

- name: Enable IPv6 forwarding
  ansible.posix.sysctl: { name: net.ipv6.conf.all.forwarding, value: 1 }
```

I understand that not everybody would need/want to have it by default. Can be put behind some option.
