### ISSUE TITLE
[BUG] Setting up a node as ephemeral makes it impossible to change it 

### ISSUE THREAD

**Issue by luizkowalski** [artis3n/ansible-role-tailscale#501]
**Describe the bug**

Hey 👋🏻 
First of all, thanks for this role, it is truly helpful!

I noticed something weird: I initially set up a node as ephemeral, and even after uninstalling and reinstalling (using `state` var), the node always returns as ephemeral.
This is my setup:

```yaml
- name: Set up tailscale
  include_role:
    name: artis3n.tailscale
  vars:
    verbose: true
    state: present
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') }}"
    tailscale_tags:
      - "server"
    tailscale_oauth_ephemeral: false
    tailscale_args: "--accept-dns=true"
    tailscale_oauth_preauthorized: true
```

Initialy, `tailscale_oauth_ephemeral` was set to true. I set the `state` to `absent` and ran the playbook. It successfully uninstalled Tailscale from my node, then set the `state` to `present` and reinstalled it. The node returned as ephemeral.

<img width="343" alt="image" src="https://github.com/user-attachments/assets/54dd31f7-ab82-4a2f-a2a7-c0221e34b574">

**Target (please complete the following information):**
 - OS: Ubuntu Server 24.04, Playbook run from MacOS
 - Ansible version: 
 ```
❯ ansible --version
ansible [core 2.15.9]
  config file = /Users/luiz/homeserver/ansible.cfg
  configured module search path = ['/Users/luiz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/luiz/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/luiz/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/luiz/Library/Python/3.9/bin/ansible
  python version = 3.9.6 (default, Feb  3 2024, 15:58:27) [Clang 15.0.0 (clang-1500.3.9.4)] (/Library/Developer/CommandLineTools/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```
 - `artis3n.tailscale` version: 4.5.0

Output of `tailscale status` during role execution (set `verbose` to true):

```bash
ok: [homeserver] => (item=tailscale_node_hostname_full) => {
    "ansible_loop_var": "item",
    "item": "tailscale_node_hostname_full",
    "tailscale_node_hostname_full": "homeserver.dolphin-marlin.ts.net."
}
ok: [homeserver] => (item=tailscale_node_hostname_short) => {
    "ansible_loop_var": "item",
    "item": "tailscale_node_hostname_short",
    "tailscale_node_hostname_short": "homeserver"
}
ok: [homeserver] => (item=tailscale_node_created_at) => {
    "ansible_loop_var": "item",
    "item": "tailscale_node_created_at",
    "tailscale_node_created_at": "2024-09-01T09:12:37.665786501Z"
}
ok: [homeserver] => (item=tailscale_node_ipv4) => {
    "ansible_loop_var": "item",
    "item": "tailscale_node_ipv4",
    "tailscale_node_ipv4": "100.111.110.112"
}
ok: [homeserver] => (item=tailscale_node_ipv6) => {
    "ansible_loop_var": "item",
    "item": "tailscale_node_ipv6",
    "tailscale_node_ipv6": "fd7a:115c:a1e0::8401:6e70"
}
ok: [homeserver] => (item=tailscale_node_tags) => {
    "ansible_loop_var": "item",
    "item": "tailscale_node_tags",
    "tailscale_node_tags": [
        "tag:server"
    ]
}
```

**Additional context**
I'm using an OAuth key to authenticate in the network
