### ISSUE TITLE
[BUG] Race condition after installing Tailscale Deb causes role to fail with "Failed to lock directory /var/lib/apt/lists" error.

### ISSUE THREAD

**Issue by sensespidey** [artis3n/ansible-role-tailscale#510]
**Describe the bug**

I'm using this role in a straightforward way to have newly-provisioned DigitalOcean droplets join my tailnet immediately after being created. I have an Ansible playbook that leverages the [ansible.digitalocean collections](https://docs.ansible.com/ansible/latest/collections/community/digitalocean/index.html) to create a droplet and associated resources. The top-level `site.yml` playbook then calls the `artis3n.tailscale` role in a way that works the *second* time:

This *almost* works the first time, but I consistently end up at the error below on a new droplet. It looks to me like a race condition where something on the system triggers an `apt-get` process (unattended-upgrades, maybe, or a cronjob?). Assuming this was coming from elsewhere in the system, I added a `pre_tasks` shell command to "manually" wait for the lock, but it doesn't help. Either way, the first time I run this for a new VM, I end up with this error:

```
<snip> (Droplet was created successfully and other tailscale tasks have already run successfully)
ok: [xx.xx.xx.xx] 
 [started TASK: artis3n.tailscale : Debian | Legacy Apt Dependencies on xx.xx.xx.xx]
 [started TASK: artis3n.tailscale : Debian | Add Tailscale Signing Key on xx.xx.xx.xx]

TASK [artis3n.tailscale : Debian | Add Tailscale Signing Key] *********************************************************************************************************************************
[WARNING]: Module remote_tmp /root/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp
dir with the correct permissions manually
changed: [xx.xx.xx.xx]
 [started TASK: artis3n.tailscale : Debian | Add Tailscale Deb on xx.xx.xx.xx]

TASK [artis3n.tailscale : Debian | Add Tailscale Deb] *****************************************************************************************************************************************
fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "msg": "Failed to lock directory /var/lib/apt/lists/: E:Could not get lock /var/lib/apt/lists/lock. It is held by process 1674 (apt-get)"}
```

If I then call the top-level `site.yml` playbook or the `tailscale.yml` specific playbook pasted above, it will run cleanly without further intervention, my droplet joins the tailnet and all is well.

This feels like a failure in the `apt` module, which ought to be able to wait for another of its own processes to release the lock. Sure enough, there's some reports along these lines upstream. [ansible#25414](https://github.com/ansible/ansible/issues/25414) appears to be the most relevant, but hasn't gone anywhere. It did give me the idea for the workaround of looking for the lock to be released before kicking off the problematic `apt` task. Unfortunately, sticking this *above* the call to the Tailscale role doesn't seem to help, and I can reliably reproduce this behaviour spinning up new droplets repeatedly.

**To Reproduce**

**NB** I'm not sure what specifics are necessary to reproduce this, but I'll do my best to describe what I suspect are the necessary components. If my hunch that it's a race condition is correct, it may well be hard to see happen in another context!

1. Top-level `site.yml` that does:
```
---
- ansible.builtin.import_playbook: playbooks/infrastructure.yml  # Provision droplets etc.
- ansible.builtin.import_playbook: playbooks/tailscale.yml       # Join tailnet and have sshd listen there
```
2. `playbooks/infrastructure.yml` something like this:
```
- name: Create a new Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ oauth_token }}"
    name: droplet1
    size: s-1vcpu-2gb
    region: tor1
    image: ubuntu-24-04-x64
    firewall: ['web']
    wait_timeout: 500
    ssh_keys: "{{ [ *** ] }}"
    id: "{{ hostvars.droplet.do_id | default(omit) }}"  ## For idempotency, we look up in inventory.
    unique_name: true  ## Simplifies idempotency for deletions.
    private_networking: true
    vpc_uuid: "{{ web_vpc.id }}"            # Use fact set in vpc.yml
    volumes: "{{ droplet1_volume.id }}"       # Use fact set in volumes.yml
  register: result
  failed_when:   ## Returns 'failure' on creation despite success. So we override.
    - result.data.droplet.id is not defined
    - "'Droplet' not in result.msg"
```
3. `playbooks/tailscale.yml` is bog standard:
```
---
- name: Join the TailScale network
  hosts: "{{ hostvars.droplet1.public_ip }}"
  remote_user: root
  gather_facts: True
  pre_tasks:
    - name: Wait for automatic system updates
      become: yes
      shell: "while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;"
  roles:
    - role: "artis3n.tailscale"
      vars:
        tailscale_authkey: "{{ vaulted_tailscale_authkey }}"
        tailscale_tags: ['infrastructure']
        verbose: true
```

**Expected behavior**

The role should finish successfully on the first run, either by waiting for the lock to be released or avoiding it being locked in the first place? I gather from the fact that my outside-the-role workaround hasn't worked, that something about the preceding tasks *within the role* are actually creating the other process that's holding the lock, so it seems to make sense to introduce a wait here. I've patched my local to introduce the same `pre_tasks` workaround mentioned above into `tasks/debian/install.yml` just before the step labeled 'Add Tailscale Deb' (which is where the failure was arising). With that extra step in place, my playbooks run cleanly the first time through.

**Target (please complete the following information):**
 - OS: Host: Ubuntu 22.04, VM: Ubuntu 24.04
 - Ansible version: 2.17
 - `artis3n.tailscale` version: v4.5.0
 - Tailscale version (set `verbose` to true): 1.76.1

Output of `tailscale status` during role execution (set `verbose` to true):

The playbook doesn't get this far :)

**Comment by sensespidey** [comment]
I notice in preparing a PR branch with my workaround/fix that there's a bunch of work on `main` since `v4.5.0` where I'm running into this. I'll test if I can reproduce the problem on main, but meanwhile I've pushed a commit and initiated a PR to illustrate the solution as it stands :)

**Comment by sensespidey** [comment]
I can confirm I'm still seeing this error when running the role at the HEAD of `main`.

**Comment by artis3n** [comment]
Hm, might I instead recommend running the check in https://github.com/artis3n/ansible-role-tailscale/pull/511/files yourself, before invoking this role?

Alternatively for cloud resources like a DigitalOcean droplet, you may want to wait for cloud init to finish as a `pre_task`, as I assume this is what is running the apt lock:

https://docs.ansible.com/ansible/latest/collections/community/general/cloud_init_data_facts_module.html

```yaml
- name: Gather all facts of cloud init
  community.general.cloud_init_data_facts:
  register: result

- name: Wait for cloud init to finish
  community.general.cloud_init_data_facts:
    filter: status
  register: res
  until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
  retries: 50
  delay: 5
```
