### ISSUE TITLE
[BUG] Installation on Fedora 42 fails

### ISSUE THREAD

**Issue by Sid-Sun** [artis3n/ansible-role-tailscale#541]
**Describe the bug**
DNF config-manager interface has changed on Fedora 41+ and Fedora | Add DNF Repo task fails with
`Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.`
```
- name: Fedora | Add DNF Repo
  become: true
  ansible.builtin.command: dnf config-manager --add-repo {{ tailscale_dnf_repos[ansible_distribution] }}
  args:
    creates: /etc/yum.repos.d/tailscale.repo
```

This change is documented here: https://docs.fedoraproject.org/en-US/quick-docs/adding-or-removing-software-repositories-in-fedora/
The equivalent command would now be:
dnf config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo

taken from https://tailscale.com/kb/1511/install-fedora-2

**To Reproduce**
1. Run the playbook against a Fedora 41+ system

**Expected behavior**
Tailscale is installed and set up

**Screenshots**

**Target (please complete the following information):**
 - OS: Fedora 42
 - Ansible version: 
 - `artis3n.tailscale` version:
 - Tailscale version (set `verbose` to true):

Output of `tailscale status` during role execution (set `verbose` to true):

```bash
ok: [instance] => {
        "tailscale_status": {
            ...
        }
    }

```

**Additional context**
