### ISSUE TITLE
Support OSX

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible-role-tailscale#60]
On Ansible 2.10 - <https://docs.ansible.com/ansible/latest/collections/community/general/mas_module.html>

<https://tailscale.com/kb/1016/install-mac>

**Comment by artis3n** [comment]
This action only support Linux-based distros. Windows and OSX users should use the GUI installations or find another role.

**Comment by kerrhome** [comment]
Latest stable macOS app: https://pkgs.tailscale.com/stable/#macos  Looks like we can unzip and move to the /Applications folder. I might do a fork and pull request.  If you have looked at this, @artis3n, and have any thoughts, please share. :)

**Comment by artis3n** [comment]
Yeah I decided this role should focus on Linux because most of the configuration options are unavailable on OSX and Windows. As far as installing goes, it felt detrimental to call the OS supported but lock out most of the role's capabilities.

If you'd like Ansible to install Tailscale on OSX, you can unzip to the Applications folder with three tasks:

```yaml
- name: Install Dependencies
  ansible.builtin.pip:
    name: github3.py
    state: present

- name: Get latest release
  # Note this module requires github3.py to be pip installed on the target
  community.general.github_release:
    user: tailscale
    repo: tailscale
    action: latest_release
  register: tailscale_version

- name: Extract Tailscale
  become: true
  ansible.builtin.unarchive:
    src: https://pkgs.tailscale.com/stable/Tailscale-{{ tailscale_version[1:] }}-macos.zip
    dest: /Applications/Tailscale.app
    remote_src: true
```

Wrote those off the top of my head, they may need some syntax tweaking.
