### ISSUE TITLE
[FEAT] advertise-exit-node support/flag

### ISSUE THREAD

**Issue by Tombar** [artis3n/ansible-role-tailscale#91]
**Is your feature request related to a problem? Please describe.**

Tailscale 1.6.0 introduced support for `--advertise-exit-node` https://tailscale.com/kb/1103/exit-nodes 

**Describe the solution you'd like**

Support to run tailscale as either an exit node or using an exit node as part of the module

**Describe alternatives you've considered**

**Additional context**

I dig into the module code and didn't really find a good place to introduce this change without a major refactor, but happy to help

**Comment by artis3n** [comment]
Agreed I'd like to add a map of flag arguments to this role so it is easy to toggle them on and off. In the meantime, however, you should be able to add `--advertise-exit-node` to `tailscale_args`: https://github.com/artis3n/ansible-role-tailscale#tailscale_args

e.g. the example:

```yaml
- name: Configure Tailscale
      include_role:
        name: artis3n.tailscale
      vars:
        tailscale_args: "--advertise-exit-node"
        # Fake example encrypted by ansible-vault
        tailscale_auth_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;tailscale
          32616238303134343065613038383933333733383765653166346564363332343761653761646363
          6637666565626333333664363739613366363461313063640a613330393062323161636235383936
          37373734653036613133613533376139383138613164323661386362376335316364653037353631
          6539646561373535610a643334396234396332376431326565383432626232383131303131363362
          3537
```
